language: python

env:
  - HASS='latest'

services:
  - docker

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_id_rsa.pub ~/travis_id_rsa.pub
  - docker pull homeassistant/home-assistant:$HASS
  - docker run --init -d --name="home-assistant" -e "TZ=Europe/Helsinki" -v /tmp:/tmp -v /tmp:/images -v $TRAVIS_BUILD_DIR:/config homeassistant/home-assistant:$HASS
  - docker ps -a

script:
  - docker exec home-assistant python -m homeassistant --script check_config --config /config

notifications:
  slack:
    secure: ej7oZKxBOkIbqZ8JNdVa1YWOtToPUoPk4q6L6LQiUlA3cUJ7dqbcwNBfaeN4PQunKbnP0VfmxrR9g45tY4z7NLNa+1/9RcmWKdVCNacdXQDlJcZ/2sDfD0LJ16cv3Eoe32Cczms5n43u8qF8eroXdgj7FGMg8RvWF/RB7cThngx4XJrV2WY6VzwxeZcFUgoLXDHKmePvk2pZTsuy1SzQ/w6FmJvLyGkb4iTHaUFr5ABfIGumCiLi0HbsNS71jqKWc+uuLnhk2lU2s9+f6cO7usmbJexDQXYffgcXQYmEt6hv3MnTsncdsj9ePVdXX8hLelCfD110UeJ/vKIFCQxkPmrqisNtNpkrYjDMrKsYRoWEHhvgmY237adhJEowlH84rQPDINh40SPugvpBnM2/nscxYQM1cjIxbRKnuiv0ccwFhq4Ac3bnkIOzyTssDtIV3pFGculuX7BEz98/HkJSOL+pSJJ7/093cQP+VNUgXM2p59350vB3YhxvRGEM0CfyYFKn+EmyupgecMBwUYAByTkfZNWdSTQFJiLI/8KZ6XCpJmFmHTPSU1A+eZZ7Jczk7ryjhl7uT0jGtBaAya0BK/4X0U+CRW+fAmu4zF8CiQ78k2rIXCQ4VARgc3NdDP4C7gIQhghkyny89CTD2vxFX6vfQUAlVhqo9up/HQkF7pA=
