# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret base_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# Weather prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
  - platform: mqtt
    name: Bridge state
    state_topic: 'zigbee2mqtt/bridge/state'
    icon: mdi:router-wireless
  - platform: seventeentrack
    username: !secret trackusername
    password: !secret trackpassword
  - platform: mitemp_bt
    mac: '58:2D:34:37:79:19'
  - platform: mqtt
    name: "Aki's weight"
    state_topic: 'miScale/Aki/weight'
    value_template: "{{ value_json['Weight'] }}"
    unit_of_measurement: 'kg'
    json_attributes_topic: 'miScale/Aki/weight'
    icon: mdi:scale-bathroom

google_assistant:
  project_id: !secret ga_project_id
  service_account: !include service_account.json
  exposed_domains:
    - light
    - group
    - climate
  entity_config:
    light.yeelight_rgb_f0b429b7e6d3:
      expose: true
      room: Living room
    light.yeelight_rgb_286c071079f6:
      expose: true
      room: Bedroom
    group.all_automation:
      expose: false
    group.all_devices:
      expose: false
    group.all_lights:
      expose: false
    switch.tv:
      expose: true
      room: Living room
    switch.blinds_bedroom:
      expose: true
      room: Bedroom
    climate.eurotronic_eur_spiritz_wall_radiator_thermostat_heat:
      expose: true
      room: Living room
    climate.eurotronic_eur_spiritz_wall_radiator_thermostat_heat_2:
      expose: true
      room: Bedroom

switch:
  - platform: broadlink
    host: !secret rm_host
    mac: !secret rm_mac
    switches:
      tv:
        friendly_name: 'TV'
        command_on: 'JgCIAQABK5QTEhMRFDYUERQRFBEUERQRFDYUNhQREzYUNhQ2FDYUNhQRFBEUNhQRExITEhQ2FDYUNhQ2ExIUNhQ2FDUTEhMSFAAFKAABKUoUAAxcAAEqSRQADFwAASpJFAAMXAABK0g='
        command_off: 'JgCIAQABK5QTEhMRFDYUERQRFBEUERQRFDYUNhQREzYUNhQ2FDYUNhQ2FBEUNhQRExITEhQ2FDYUERQ2FBEUNhQ2FDUUERQRFAAFKAABKUoUAAxcAAEqSRQADFwAASpJFAAMXAABK0g='
      blinds_bedroom:
        friendly_name: 'Bedroom curtain'
        command_on: 'sgCqAnxQNwoWChYLCxUWCgwVCxUWCwsVDBULFQsWCxUWCwsVFgsLFRYKDBULFQwUFwoLFgsVCxUXCgsWCxULFQwVCxUMFQsVDBULFRYLCxUWCwsVFgsLFbhRNgoWChYLCxUXCgsVDBUWCgsWCxULFQwVCxUWCwsVFgsLFRYKDBULFQwVFgoMFQsVCxYWCgsVDBULFQwVDBULFQsVDBULFRcKCxUWCwsVFgoMFRaiUTYKFgsWCgsVFgsMFAwVFgoMFQsVDBULFQwVFgoMFBcKCxUWCwsVCxYLFRYLCxULFgsVFgoMFQwUDBULFQwVCxUMFQsVDBUWCgsVFgsLFRYLCxUWo1A2ChcKFgoMFRYKCxYLFRYLCxULFQwVCxUMFRYKDBUWCgwUFgsMFQsVDBQWCwsVDBULFRYKDBUMFQsVCxUMFQsVDBUMFAwVFgoMFBcKCxYWCgwUFqNQNwkXChYKDBUWCgwVCxUWCwsVDBULFQwVCxUWCgwVFgsLFRYKDBULFQwVFgoMFQsVCxUXCgwVCxULFQwVCxUMFQsVDBULFRYKDBUWCgwVFgoMFRaiUDYLFgoWCwsVFgoMFQwUFgsMFAwVDBULFQsVFgsLFRYLCxUWCgwVDBULFRYKDBULFQwVFgoMFAwVDBULFQwUDBULFQwVCxUWCgwVFgsLFRYKDBUWolA3ChYKFwoLFRYLCxUMFRYKDBULFQwUDBUMFRYKCxUWCwsVFgsLFQwUDBUWCwsVDBQMFRYKDBULFQwVDBQMFQsVDBULFQwVFgoMFBcKCxUXCgwUFqJRNgoWChcKDBQWCwsVDBUWCgwVCxUMFQsVDBUWCgwUFwoLFhYKCxYLFQwUFwoLFQwVCxUWCwsVDBQMFQsWCxUMFAwVCxUMFRYKDBUWCgwUFwoMFBYABdwAAAAAAAAAAAAAAAAAAA==='
        command_off: 'sgCvAn1RNgoWCxYKCxYVCwsWCxUWCgwVCxUMFQsVDBUWCgsWFQsLFhYKCxYLFQsVCxYLFRYLFgoWCwsVCxYLFQsVDBULFgsVCxULFhULCxUMFRYLCxUWCxUEoFE2CxULFgsKFhYKCxYLFRYLCxULFQwVCxYKFhYKCxYVCwsWFQsLFQwVCxULFgsVFgsWChYLCxULFgoWCxYLFQsVDBULFQwVFgoLFgsVFgoMFRYKFgShUDYLFgoWCwsVFgsLFQsWFQsLFQsVDBULFgsVFgoMFRYKDBUWCgsWCxULFgsVCxYVCxULFgsLFQsWCxULFgsVCxYLFQsVDBUWCgwVCxUWCwsVFgq4UTYKFwoWCwsVFQwKFgsVFgsLFQsWCxULFgsVFQwLFRYKDBUWCgsWCxULFgsVCxYVCxYKFgsLFQsWCxULFQwVDBULFQsVCxYWCwoWCxUWCwsVFgsVBKBSNQsWChYLCxUWCgwVCxYVCwsVDBULFQwVCxUWCwsVFgoMFRULDBULFgoWCxULFRYLFgsWCgsWCxULFQwVCxUMFQsVCxYLFRYKDBULFRYLCxUWCxUEoVA2CxULFgsLFRYLCxULFRYLCxYLFQsVDBULFRYLCxUWCwsVFgsKFgsVDBULFQsWFQsWChYLDBULFQsVCxYLFgsVCxUMFQsVFgsLFQsVFgsLFRYLFQSgUjULFgoWCwsVFgsLFQwVFQsMFQsVCxUMFQsWFQsLFRYLCxUWCwsVDBULFQsVDBUWChYLFgoLFgsVCxYLFQwVCxULFQsWCxUWCwsVDBUVCwsWFQsWolE1CxYKFgsLFRYLCxULFRcKCxYLFQsVDBULFhULCxUWCwsVFgsLFQsWCxULFQwVFgoWCxYKCxYLFQsWCxULFgsVCxYLFQsVFgsLFQwVFgoLFhULFgAF3AAAAAAAAAAAAA==='

mqtt:
  discovery: true
  broker: 192.168.1.10
  username: 'mqtt'
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

zwave:
  usb_path: /dev/ttyACM1
  config_path: /share/open-zwave/config/

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.100-255

ifttt:
  key: !secret ifttt_key

yeelight:
  devices:
    192.168.1.22:
      name: Living room light
      model: color1

transmission:
  host: !secret transmission_ip
  username: !secret transmission_username
  password: !secret transmission_password

system_health:

influxdb:
  host: 192.168.1.3
  port: 8086
  database: home_assistant
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - light
      - sensor
      - switch
      - zwave
  tags:
    instance: prod
    source: hass

pi_hole:
  host: !secret pihole_host

mobile_app:

rest_command:
  shutdown_ps:
    url: !secret PS_shutdown_url
    method: GET
  restart_ps:
    url: !secret PS_restart_url
    method: GET
