homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 54.68916
  longitude: 25.2798
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vilnius
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: True
  trusted_proxies:
  - 127.0.0.1
  - ::1 
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless

# Text to speech
tts:
  - platform: google
    base_url: !secret base_url

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

google_assistant:
  project_id: !secret ga_project_id
  api_key: !secret ga_api_key
  exposed_domains:
    - light
    - group
    - climate
  entity_config:
    light.yeelight_rgb_f0b429b7e6d3:
      expose: true
      room: Living room
    light.yeelight_rgb_286c071079f6:
      expose: true
      room: Bedroom
    group.all_automation:
      expose: false
    group.all_devices:
      expose: false
    group.all_lights:
      expose: false
    switch.tv:
      expose: true
      room: Living room
    switch.blinds_bedroom:
      expose: true
      room: Bedroom
    climate.eurotronic_eur_spiritz_wall_radiator_thermostat_heat:
      exposure: true
      room: Living room
    climate.eurotronic_eur_spiritz_wall_radiator_thermostat_heat_2:
      exposure: true
      room: Bedroom


switch:
  - platform: broadlink
    host: !secret rm_host
    mac: !secret rm_mac
    switches:
      tv:
        friendly_name: 'TV'
        command_on: 'JgCIAQABK5QTEhMRFDYUERQRFBEUERQRFDYUNhQREzYUNhQ2FDYUNhQRFBEUNhQRExITEhQ2FDYUNhQ2ExIUNhQ2FDUTEhMSFAAFKAABKUoUAAxcAAEqSRQADFwAASpJFAAMXAABK0g='
        command_off: 'JgCIAQABK5QTEhMRFDYUERQRFBEUERQRFDYUNhQREzYUNhQ2FDYUNhQ2FBEUNhQRExITEhQ2FDYUERQ2FBEUNhQ2FDUUERQRFAAFKAABKUoUAAxcAAEqSRQADFwAASpJFAAMXAABK0g='
      blinds_bedroom:
        friendly_name: 'Bedroom curtain'
        command_on: 'sgCqAnxQNwoWChYLCxUWCgwVCxUWCwsVDBULFQsWCxUWCwsVFgsLFRYKDBULFQwUFwoLFgsVCxUXCgsWCxULFQwVCxUMFQsVDBULFRYLCxUWCwsVFgsLFbhRNgoWChYLCxUXCgsVDBUWCgsWCxULFQwVCxUWCwsVFgsLFRYKDBULFQwVFgoMFQsVCxYWCgsVDBULFQwVDBULFQsVDBULFRcKCxUWCwsVFgoMFRaiUTYKFgsWCgsVFgsMFAwVFgoMFQsVDBULFQwVFgoMFBcKCxUWCwsVCxYLFRYLCxULFgsVFgoMFQwUDBULFQwVCxUMFQsVDBUWCgsVFgsLFRYLCxUWo1A2ChcKFgoMFRYKCxYLFRYLCxULFQwVCxUMFRYKDBUWCgwUFgsMFQsVDBQWCwsVDBULFRYKDBUMFQsVCxUMFQsVDBUMFAwVFgoMFBcKCxYWCgwUFqNQNwkXChYKDBUWCgwVCxUWCwsVDBULFQwVCxUWCgwVFgsLFRYKDBULFQwVFgoMFQsVCxUXCgwVCxULFQwVCxUMFQsVDBULFRYKDBUWCgwVFgoMFRaiUDYLFgoWCwsVFgoMFQwUFgsMFAwVDBULFQsVFgsLFRYLCxUWCgwVDBULFRYKDBULFQwVFgoMFAwVDBULFQwUDBULFQwVCxUWCgwVFgsLFRYKDBUWolA3ChYKFwoLFRYLCxUMFRYKDBULFQwUDBUMFRYKCxUWCwsVFgsLFQwUDBUWCwsVDBQMFRYKDBULFQwVDBQMFQsVDBULFQwVFgoMFBcKCxUXCgwUFqJRNgoWChcKDBQWCwsVDBUWCgwVCxUMFQsVDBUWCgwUFwoLFhYKCxYLFQwUFwoLFQwVCxUWCwsVDBQMFQsWCxUMFAwVCxUMFRYKDBUWCgwUFwoMFBYABdwAAAAAAAAAAAAAAAAAAA==='
        command_off: 'sgCvAn1RNgoWCxYKCxYVCwsWCxUWCgwVCxUMFQsVDBUWCgsWFQsLFhYKCxYLFQsVCxYLFRYLFgoWCwsVCxYLFQsVDBULFgsVCxULFhULCxUMFRYLCxUWCxUEoFE2CxULFgsKFhYKCxYLFRYLCxULFQwVCxYKFhYKCxYVCwsWFQsLFQwVCxULFgsVFgsWChYLCxULFgoWCxYLFQsVDBULFQwVFgoLFgsVFgoMFRYKFgShUDYLFgoWCwsVFgsLFQsWFQsLFQsVDBULFgsVFgoMFRYKDBUWCgsWCxULFgsVCxYVCxULFgsLFQsWCxULFgsVCxYLFQsVDBUWCgwVCxUWCwsVFgq4UTYKFwoWCwsVFQwKFgsVFgsLFQsWCxULFgsVFQwLFRYKDBUWCgsWCxULFgsVCxYVCxYKFgsLFQsWCxULFQwVDBULFQsVCxYWCwoWCxUWCwsVFgsVBKBSNQsWChYLCxUWCgwVCxYVCwsVDBULFQwVCxUWCwsVFgoMFRULDBULFgoWCxULFRYLFgsWCgsWCxULFQwVCxUMFQsVCxYLFRYKDBULFRYLCxUWCxUEoVA2CxULFgsLFRYLCxULFRYLCxYLFQsVDBULFRYLCxUWCwsVFgsKFgsVDBULFQsWFQsWChYLDBULFQsVCxYLFgsVCxUMFQsVFgsLFQsVFgsLFRYLFQSgUjULFgoWCwsVFgsLFQwVFQsMFQsVCxUMFQsWFQsLFRYLCxUWCwsVDBULFQsVDBUWChYLFgoLFgsVCxYLFQwVCxULFQsWCxUWCwsVDBUVCwsWFQsWolE1CxYKFgsLFRYLCxULFRcKCxYLFQsVDBULFhULCxUWCwsVFgsLFQsWCxULFQwVFgoWCxYKCxYLFQsWCxULFgsVCxYLFQsVFgsLFQwVFgoLFhULFgAF3AAAAAAAAAAAAA==='

mqtt:
  discovery: true
  username: 'aki_mqtt'
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

zwave:
  usb_path: /dev/ttyACM1
  config_path: /share/open-zwave/config/

# This has been commented because 
# asuswrt:
#    host: 192.168.1.1
#    username: !secret device_username
#    ssh_key: !secret device_ssh_key

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.100-255

ifttt:
  key: !secret ifttt_key
